services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
    networks:
      - itsm-network

  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    volumes:
      - ./prisma:/db
      - ./backups:/backups
    networks:
      - itsm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - itsm-network

networks:
  itsm-network:
    driver: bridge
